---
- name: "Install kubernetes-cni"
  package:
    pkg: "{{ install_kubernetes_cni_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "kubernetes-cni"
